[[edge_functions]]
function = "auth"
path = "/api/login"
method = "POST"

[[edge_functions]]
function = "auth"
path = "/api/logout"
method = "POST"

[[edge_functions]]
function = "index"
path = "/api/asignar-puntos"
method = "POST"

[[edge_functions]]
function = "cliente"
path = "/api/cliente"
method = "GET"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"